# Generated by Django 5.2.8 on 2025-12-18 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_type', models.CharField(choices=[('STRAIGHT', 'Numéro plein'), ('COLOR', 'Couleur'), ('LOWHIGH', '1-18 / 19-36'), ('EVENODD', 'Pair / Impair'), ('DOZEN', 'Douzaine'), ('COLUMN', 'Colonne')], max_length=20)),
                ('value', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('won_amount', models.IntegerField(default=0)),
                ('drawn_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
